### ISSUE TITLE
Annuaire des membres

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane#2]
Ajouter une vue listant les membres locaux pour favoriser la découverte de nouveaux profils

**Comment by Cl0v1s** [comment]
En ce qui concerne l'ajout de nouvelles vues, tu penses avoir le temps/l'envie de créer une petite maquette aussi ? 

C'est vraiment pas mon truc, et j'ai peur de faire de la merde :/

**Comment by Dehelssey** [comment]
No souci. J'suis pas chez moi ce weekend et cette semaine j'ai zéro remote mais je vais tenter de te faire ça !

**Comment by Dehelssey** [comment]
**Quelques références pour l'affichage des profils dans l'annuaire :** 
vue profil perso quand on est sur l'accueil de BDX.town :
![image](https://user-images.githubusercontent.com/20315413/127572376-21a9a333-9180-467e-bdad-8eaa3d198044.png)

vue d'un profil au survol de l'avatar d'une personne sur un fil :
![image](https://user-images.githubusercontent.com/20315413/127572386-896356cf-8d58-4991-8c2a-5f181587b63a.png)

J'ai le sentiment que le nombre d'abonné·e·s et d'abonnements _ne sont pas des datas utiles pour décider ou non de suivre une personne._ Le nombre de publications est un indicateur (on peut ne pas souhaiter suivre quelqu'un qui poste trop, ou à l'inverse, suivre des gens actifs) mais il n'est pertinent qu'avec une date d'inscription. Sauf qu'on s'en fout un peu de quand s'est inscrite la personne. Du coup une data de type **"nb de posts par jour"** serait l'idéal (un seul chiffre à afficher, à vraie valeur ajoutée) (mais ptet compliqué à récupérer ?)

La data **"dernière activité"** (présente sur masto) est cool aussi pour éviter de follow des comptes délaissés...
![image](https://user-images.githubusercontent.com/20315413/127572912-3d084d17-d929-40d8-8c50-b2578e8e17d3.png)

**Concernant la page annuaire** (et pas juste la carte profil), Misskey et Mastodon proposent des vues filtrées (actifs récemment, profils épinglés, nouvelles/nouveaux...)
![image](https://user-images.githubusercontent.com/20315413/127573010-8d1520d9-5f0f-4431-a213-f7a51d2b57b0.png)
![image](https://user-images.githubusercontent.com/20315413/127573040-87ab3b91-a1c2-4b29-8c60-d2392b769310.png)

Compte-tenu de ces différentes considérations j'ai tenté différents rendus : 
![image](https://user-images.githubusercontent.com/20315413/127573246-3baba388-151a-44e9-8175-4065f089a845.png)
rejeté car les datas affichées ne me paraissent pas les plus utiles comme je le disais 
et l'affichage de la bio en respectant la mise en forme ne permet pas d'en lire suffisamment.

2ème jet : 
![image](https://user-images.githubusercontent.com/20315413/127573337-686d7e9d-c175-4d0f-891b-5cfa1fa90220.png)
on casse la mise en forme de la bio (suppression des sauts de ligne). Gain de place. 

3ème jet : 
![image](https://user-images.githubusercontent.com/20315413/127573458-9c02194a-056a-4555-ac6b-1aaa67934f56.png)
c'est là que j'ai fait sauter la data "inutile" pour ne garder que le nb de messages et la dernière activité
l'ensemble me parait plus équilibré

4ème jet :
![image](https://user-images.githubusercontent.com/20315413/127573519-dec76c7c-5f96-46d1-89f8-cdb4f9c45c7e.png)
une décli de la v3 en allégant la construction PSEUDO / @handle@instance sur une seule ligne. 
**problème :** certaines personnes ont un pseudo qui diffère de leur handle...

5ème jet :
![image](https://user-images.githubusercontent.com/20315413/127573822-846b79de-04a9-40d7-8d98-68cb642a15a6.png)
une version minimaliste : zéro data, juste le pseudo le handle et la bio. On peut même donner plus de place à la bio si nécessaire. Je crois que c'est ma version préférée mais...

car il y a un mais.

![image](https://user-images.githubusercontent.com/20315413/127573888-97e49f23-0677-492c-b65c-aebab2d7e1de.png)
ça fait vide si l'utilisateur a une mini bio (et pire encore si pas de bio...)

Je pense que niveau interface c'est mieux d'avoir une hauteur fixe de carte, je pense qu'une grille serait plus claire et lisible qu'une construction en masonry avec des cartes à hauteur variable...

la v3 (avec data en bas de carte) casse un peu cette impression de vide dans ce cas là 
![image](https://user-images.githubusercontent.com/20315413/127573981-0ac82071-411e-494d-9f54-cc0ee56f1fb8.png)

---

Bref 
je vais pas trancher tout seul ce soir ^^ #HELP

**Comment by Dehelssey** [comment]
j'ai ptet un compromis : 
![image](https://user-images.githubusercontent.com/20315413/127574301-56de9212-b560-4bc6-a2aa-cdb6a787e89e.png)
pas de data, juste la dernière co, mais ça permet d'habiller la carte quand peu ou pas de bio
![image](https://user-images.githubusercontent.com/20315413/127574357-0733e2d1-8b1b-45bc-8bcc-9a22bf4beaf1.png)

**Comment by Dehelssey** [comment]
après je me posais aussi la question d'utiliser un picto plutôt qu'un bouton suivre / ne plus suivre mais c'est pas cohérent avec l'UI soapbox

d'ailleurs le bouton "ne plus suivre" je l'ai designé un peu plus discret que le "suivre" 
![image](https://user-images.githubusercontent.com/20315413/127574474-bb877da5-d799-4fc1-9c5d-251c6313814f.png)

**Comment by Dehelssey** [comment]
quelque soit la version choisie on peut, pour la bio, soit tronquer le texte [...] soit, mais je sais pas si c'est pertinent, proposer un scroll ?

**Comment by Dehelssey** [comment]
bon j'arrive pas à aller me coucher sans avoir "fini" donc voilà la vue complète pour le moment
![image](https://user-images.githubusercontent.com/20315413/127575949-0f737202-8587-47a2-b451-149e7f804311.png)
je suis parti de la vue "bookmarks" (la même que "demande de suivi" par ailleurs)
j'ai rajouté une entrée dans la sidebar pour y accéder avec l'icone font-awesome "users" 

demain je fais une v2 avec des filtres.
et au lieu de "dernière activité" on peut ptet juste afficher un tag "en ligne" ? ou alors en plus ?

bref j'ai pas fini en fait >_<
et n'hésite pas à me dire ce qui est techniquement faisable ou pas aussi, accessoirement ^^

**Comment by Dehelssey** [comment]
pour info j'ai testé le suivre / ne plus suivre avec picto (parce qu'en fait y'a bien une vue sur l'UI ou ces icones existent) mais au final c'est pas mieux. je trouve le bouton plus clair et efficace.

![image](https://user-images.githubusercontent.com/20315413/127611964-a9f0f5f9-4b04-4e44-baf0-3a93ae3a9a01.png)

en revanche le badge 'en ligne' ça peut le faire. Pareil j'avais essayé avec juste un indicateur (idéalement animé) mais en fait c'est pas explicite, donc si c'est pas clair et que y'a la place ➜ label.

**Comment by Dehelssey** [comment]
allez version finale : 
![image](https://user-images.githubusercontent.com/20315413/127615837-f6ad102f-cb91-48ec-8731-4e48cd274950.png)
j'ai utilisé des toggles pour conserver des composants de l'UI existante

par défaut j'ai supposé que les profils étaient affichés par date de dernière connexion. Du coup le toggle permet d'activer pour voir les derniers inscrits (j'ai opté pour nouvelles recrues pour que le terme soit non genré)
_Si le tri par défaut des profils est aléatoire et qu'il faut pouvoir gérer plus d'options (dernière co, date d'inscription, "populaires" comme sur Misskey) je reverrai ma copie avec des boutons radio mais faudra les styliser parce que les seuls radio présents sur l'interface sont en mode skin natif du navigateur..._

le second toggle est assez explicite, il permet de n'afficher que les profils de l'instance.

Évidemment si on décide de n'afficher **de toutes façons** que les profils BDX.town je ferai sauter ce toggle ¯\_(ツ)_/¯

**Comment by Cl0v1s** [comment]
Je trouve ta réflexion sur les informations super pertinente. Le nombre de follow/followers est vraiment osef, c'est pas utile si on veut une communauté basée sur l'intérêt ! 

Concernant le petit badge "en ligne", c'est une bonne idée, mais on a pas l'info (tu peux regarder dans le chat, on ne sait pas quand un user est en ligne ou pas. Du coup, pas possible de l'afficher sans un gros travail du coup je sais pas si c'est pertinent.

Etant donné la présence du toggle "bdx.town" seulement, j'imagine que tu verrais la vue capable d'afficher d'autres profils que ceux de bdx.town ? Comment tu vois cette fonctionalité ?

**Comment by Dehelssey** [comment]
1. bon ben on est d'accord : **on fait sauter les chiffres** ^^

2. **le badge en ligne** c'est inspiré de Misskey mais effectivement si on n'a pas l'info et que c'est une usine à gaz de la récupérer alor osef. C'était un bonus (pour inciter au chat par ex) mais pas indispensable.

3. pour **la vue des profils**, que ce soit Masto ou Misskey, leurs annuaires respectifs ne se limitent pas à l'instance locale, ils vont chercher les profils qui fédèrent. Pour moi ça a la même gueule que ce soit profils locaux ou profils fédérés, c'est juste un filtre pour resserrer la recherche. 

Je sais pas techniquement parlant comment on peut récupérer la liste des profils, je suis juste parti du principe que par défaut la requête allait chercher tous les profils fédérés (puisque c'est la solution choisie par les deux autres acteurs majeur du fedi) et que, pour notre volonté de "local" c'était pertinent de pré-filtrer BDXtown (mais sans pour autant bloquer les comptes extérieurs)

**Comment by Cl0v1s** [comment]
D'accord, je vois pour le 3, je pense effectivement que c'est une bonne chose de montrer les profils fédérés si ça ne complique pas trop les choses niveau développement, je me documente sur la DOC pour savoir comment faire !

**Comment by Dehelssey** [comment]
@Cl0v1s je suis impardonnable, j'ai 3 mois de retard dans ma réponse lol
J'ai un Xd ça irait ?

**Comment by Cl0v1s** [comment]
Et encore trois mois de retard ! 

Si je peux l'ouvrir sans acheter XD, Oui !

**Comment by Cl0v1s** [comment]
Suivre ici: https://github.com/Cl0v1s/mangane-ui/issues/15
