### ISSUE TITLE
Se souvenir de la position dans le fil quand on fait "retour"

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane#24]
Dès qu'on consulte un pouet et qu'on appuie sur le bouton "retour" on est ramenés plus haut sur la timeline, voire tout en haut.

Je ne sais pas à quel point c'est possible/complexe de sauvegarder le scroll ?

**Comment by Cl0v1s** [comment]
Fixé dans la dernière version à priori

**Comment by Dehelssey** [comment]
Ça a l'air mieux oui \o/
