### ISSUE TITLE
Noms de variable au lieu de texte dans l'onboarding

### ISSUE THREAD

**Issue by PAUL-BERNARD** [Cl0v1s/mangane#26]
Je viens d'ouvrir Bdx.town après un petit moment, et il y a ce qui me semble être un encadré de présentation de l'instance. Je n'ai pas de texte en clair sur cet encadré, seulement des noms de variable comme "enlistment.step0.title"

![image](https://user-images.githubusercontent.com/74709745/186255536-14e327f4-06df-4f1d-ae56-0193e6e41d66.png)

L'onglet Network des outils de développement n'indique pas de requête bloquée, et Privacy Badger bloque seulement une image provenant de mozilla.org.

Voilà la sortie de la console

![image](https://user-images.githubusercontent.com/74709745/186257519-b5a10e03-ea87-4525-a4de-b65041fcf9de.png)

**Comment by Dehelssey** [comment]
J'ai eu le même problème, c'est parce que l'onboarding n'a été configuré qu'en français. Si l'interface est dans une autre langue chez toi Mangane ne trouve pas les contenus à afficher à la place des variables.

@Cl0v1s est dessus !

**Comment by Cl0v1s** [comment]
Effectivement, merci @Dehelssey ! 

C'est un duplicata de cette issue du coup https://github.com/Cl0v1s/mangane-ui/issues/29
Merci pour ton enquête @PAUL-BERNARD

**Comment by PAUL-BERNARD** [comment]
> Effectivement, merci @Dehelssey !
> 
> C'est un duplicata de cette issue du coup [Cl0v1s/mangane-ui#29](https://github.com/Cl0v1s/mangane-ui/issues/29) Merci pour ton enquête @PAUL-BERNARD

Oups, j'aurais peut-être dû faire un peu plus de recherche dans les issues... 😵‍💫

En attendant la traduction en anglais, il faudrait peut-être mettre l'interface en français par défaut si la langue de l'utilisateur n'est pas disponible ? Sinon le problème subsistera pour celui qui a son navigateur en espagnol, nahuatl ou espéranto.

**Comment by Cl0v1s** [comment]
On a pas la main sur ce paramètre, l'UI se base sur l'interface du navigateur et faire un workaround serait trop touchy. Je vais juste ajouter les traductions par défaut, c'est rapidement réglé :)
