### ISSUE TITLE
Toujours ajouter les @ des gens mentionnés en réponse 

### ISSUE THREAD

**Issue by Cl0v1s** [Cl0v1s/mangane#27]

**Comment by Dehelssey** [comment]
Apparemment GlitchSoc propose un élément visuel qui indique qu'un pouet est une réponse donc la mention **dans** le message n'est pas foncièrement nécessaire... 

![eb2d640ecf924f4c](https://user-images.githubusercontent.com/20315413/198848759-a95be796-34c2-48f2-83d9-89c49bd510b4.png)

C'est la ptite icone "bulle". Oui c'est discret.

**Comment by Dehelssey** [comment]
J'ai ouvert un ticket sur le repo masto pour qu'ils mettent la mention "en réponse à" sur la version web de leur UI, vu que c'est déjà implémenté sur leurs appss.

**Comment by Cl0v1s** [comment]
Merci pour le ticket chez masto, en attendant je pense qu'on va quand même devoir se plier à l'usage majoritaire, vu l'hostilité que ça peut générer chez les copains

**Comment by Dehelssey** [comment]
Ouais clairement on peut attendre longtemps qu'ils se réveillent anyway...

Mais bon apparemment y'a une volonté de @Gargron d'uniformiser les interfaces webapp et apps mobiles (entre autres sur les icones) ça peut ptet aboutir sur une gestion similaire des "reply-to" 👍
