### ISSUE TITLE
Titre de la vue #Hashtag

### ISSUE THREAD

**Issue by Cl0v1s** [Cl0v1s/mangane#41]
Le titre n'est pas présenté correctement sur mobile.

![Screenshot_20221103-212955.png](https://user-images.githubusercontent.com/917518/199827813-9e454792-e179-42f9-991e-5acd23703eec.png)

**Comment by Dehelssey** [comment]
un peu trop près du bord supérieur en effet. Tu vois autre chose ? 🤔
