### ISSUE TITLE
Amélioration procédure d'installation a destination des installations OTP

### ISSUE THREAD

**Issue by zoski** [Cl0v1s/mangane#42]
La procédure d'installation donne :

> busybox unzip static.zip -o -d /opt/pleroma/instance

Mais les installation OTP n'ont pas de dossier instance correspondant. D'après la [documentation](https://docs-develop.pleroma.social/backend/configuration/static_dir/) le frontend est a déposer dans le static_dir soit : /var/lib/pleroma/static dans ce cas.

La commande équivalente serait :
`unzip static.zip -d /var/lib/pleroma/static` dans le cas où les statics sont bien dans la destination par défaut.

**Comment by Cl0v1s** [comment]
Qu'est ce que tu penses de proposer de passer par la commande OTP dédiée ? 

https://docs.akkoma.dev/stable/administration/CLI_tasks/frontend/

Il suffit à priori de mettre le contenu dans un sous-répertoire dist. Ca permettrait aussi de pas dépendre de la config mais du code de pleroma !

**Comment by zoski** [comment]
En effet, j'ai pas essayé la commande officielle. Mais ça devrait marcher.

**Comment by Cl0v1s** [comment]
Je suis en train de créer un pipeline lors du merge sur master, en fait de base le build en mode prod ne pointe pas vers un site particulier et tape dans le /api du domaine sur lequel il est déployé. 

Donc normalement à l'avenir on devrait avoir réglé le pb de bdx.town en dur + je vais modifier le readme pour parler de la commande OTP + Mix officielle

**Comment by Cl0v1s** [comment]
On a le pipeline qui fonctionne ! Je mets à jour les instructions et on est bons !

**Comment by zoski** [comment]
Super merci :pray:
