### ISSUE TITLE
Amélioration de l'UI des sondages

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane#45]
## problèmes

Actuellement les sondages affichent des radio buttons même quand la question est à choix multiple. C'est contre-intuitif au possible.

![Screenshot_20221107-195519_Vivaldi_Browser](https://user-images.githubusercontent.com/20315413/200391752-63afd8cf-16d3-4fdc-a111-b6be1ea4ecb5.png)

Par aillieurs le fond orange c'est pas foufou. Le sondage a pas besoin d'un fond, amha.

## solution
Il faudrait donc des checkboxes au lieu de boutons radio quand sondage choix multiple + virer le bg

(En revanche c'est bien géré le toggle pour passer de l'un a l'autre quand on en crée un, plutôt que l'appui long sur un des champs adopté par masto -_-)

**Comment by Cl0v1s** [comment]
C'est déjà des checkbox non ? Je suis pas sûr de comprendre

**Comment by Dehelssey** [comment]
Pardon, en code oui vu que multi select mais les conventions c'est checboxes (multiselect) carrées et boutons radios (choix unique) ronds.

Là ça reste rond dans tous les cas donc aucune indication si on a plusieurs choix ou pas
