### ISSUE TITLE
Update nom du repo et lien sur les instances Mangane

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane#47]
Pendant un moment on avait Mangane-back et Mangane-UI mais si on se concentre sur le front, qui selon moi est le cœur de ce qui différencie Mangane, on devrait ptet

1. renommer le repo Mangane tout court sans le -ui
2. mettre un lien vers ce repo sur l'interface de l'instance parce qu'actuellement ça redirige vers https://github.com/Cl0v1s/Akkoma (ce qui peut créer la confusion puisque c'est écrit Mangane sur le lien)

**Comment by Dehelssey** [comment]
(je sais que tu m'as filé les droits mais je veux pas risquer de péter un truc en renommant le repo... je sais même pas si ça fait partie des trucs sur lesquels j'ai la main...^^

**Comment by Cl0v1s** [comment]
En fait je pense que si on renomme ce repo en mangane, ça devrait s'update tout seul dans l'UI visible, je test

**Comment by Cl0v1s** [comment]
C'est fixé :)
