### ISSUE TITLE
Virer la vue multi-colonnes de masto ?

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane#6]
Si ça alourdit inutilement^^ Sauf si certaines personnes s'en servent hein

**Comment by Cl0v1s** [comment]
A voir l'impact, étant donné que le frontend est en fait une SPA, le conserver ne pose pas de soucis majeur, étant donné pour le serveur, qu'on passe par cette SPA ou une autre ne change pas grand chose.
