### ISSUE TITLE
Retirer l'onglet "favoris" du profil

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane#63]
Sur mangane on a un onglet "favoris" sous la bio sur la page profil... 

Je suis pas sûr que ce soit une bonne idée de rendre les likes des gens publics. Y'a que moi que ça met mal à l'aise ?

En fait je trouve ça, au mieux inutile au pire intrusif.

**Comment by Cl0v1s** [comment]
Je te suis tu peux mettre la milestone goodcook-raccoon !

Le 12 novembre 2022 17:12:32 GMT+01:00, "Guérin" ***@***.***> a écrit :

**Comment by Cl0v1s** [comment]
Avec vérification, il se trouve que l'on peut uniquement voir ses favoris sur son propre profil

<img width="624" alt="image" src="https://user-images.githubusercontent.com/917518/201547889-5d116979-593c-400b-8968-2b6ed860efd3.png">

Confirmé par le code: 
```
 if (account) {
    const ownAccount = account.id === me;
    if (ownAccount || !account.pleroma.get('hide_favorites', true)) {
      tabItems.push({
        text: <FormattedMessage id='navigation_bar.favourites' defaultMessage='Likes' />,
        to: `/@${account.acct}/favorites`,
        name: 'likes',
      });
    }
  }
```

**Comment by Dehelssey** [comment]
Lol oops le boulet ^^
