### ISSUE TITLE
Prévoir un onboarding pour les nouveaux membres

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane#9]
à la manière de l'onboarding sur masto, prévoir deux trois "slides" qui présentent vite fait l'interface et les différents onglets pour faciliter l'arrivée sur bdx.town de gens non connaisseurs du fediverse.

➜ le rendre optionnel (un bouton "je connais déjà" en plus du bouton "suivant" sur la première vue
➜ présenter les trois "fils" (perso / local / fediverse)
➜ présenter le mode chat ?
➜ présenter les réglages ? les options de confidentialité sur le profil ?

alternative : on fait une mini doc genre sur notion ou quoi et on automatise un message de bienvenue via Filip Toutou (en chat justement ?)

on pourrait également épingler un message sur son profil qui reprendrait les bases ?

Je m'occupe des masquettes asap @Cl0v1s

**Comment by Cl0v1s** [comment]
Le fil fédiverse sera renommé le fil "Découvrir" pour la 1.3.1 de bdx.town-fe ! 

Ce serait pas mal également de prévoir une sélection de thématiques telle que présentes sur Trunk, pour suggérer quelques comptes au hasard en fonction des thématiques choisies (en précisant que ces préférences ne sont pas conservées, et que les comptes sont purement choisis au hasard à partir de Trunk). 


Ca permettrait de contrer le fait que, pour le moment notre TL "Découvrir" est quand même vachement orienté Tech

**Comment by Dehelssey** [comment]
Ouais le "découvrir" est ptet pas idéal...

"Reste du monde" ? "Fil public" ?

**Comment by Dehelssey** [comment]
Et d'ailleurs on part sur un onboarding "simple" (comme sur masto actuellement) un petit slider d'infos au lancement de l'app pour la première fois ou sur un onboarding dynamique avec l'info qui s'affiche quand tu interagis avec l'élément associé

**avantages du simple :** 
- plus facile à intégrer
- immanquable

**inconvénient :** 
- risque de trop d'infos d'entrée de jeu (et pas au bon moment ?)

**avantages du dynamique :** 
- moins intrusif
- plus pertinent puisque l'aide apparait pile quand t'en as besoin

**inconvénient :** 
- risque de ne pas être découvert^^

dans un souci de praticité je partirai sur un onboarding simple, à la première connexion, qui va à l'essentiel.
- option de skipper 
- option pour en savoir + après l'onboarding de base
- élément cliquable dans l'UI pour le rejouer

**Comment by Cl0v1s** [comment]
Déplacé dans Mangane-UI https://github.com/Cl0v1s/mangane-ui/issues/9
